# Generated by Django 3.1.7 on 2021-04-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('lang', models.CharField(default='null', max_length=20)),
                ('imdb', models.CharField(default='Not available', max_length=20)),
                ('release', models.CharField(default='null', max_length=20)),
                ('imgsrc', models.URLField(default='null')),
                ('ott', models.URLField(default='null')),
                ('link', models.URLField(default='null')),
                ('titleType', models.CharField(max_length=50)),
            ],
        ),
    ]
